version: '3.8'

services:
  api:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
      dockerfile: apps/api/Dockerfile
    container_name: bemodest-api
    restart: always
    ports:
      - 32358:32358
    env_file:
      - apps/api/.env

  sidecar:
    build:
      context: .
      dockerfile: apps/sidecar/Dockerfile
    container_name: bemodest-sidecar
    restart: always
    ports:
      - 32359:32359
    env_file:
      - apps/api/.env
